
export audioToolsDir="${__current_module_dir:-$HOME/tools/audio-tools}"

if [ -d "$audioToolsDir/bash/functions" ]; then
    for functionFile in $audioToolsDir/bash/functions/*sh; do
        # Note: Sourcing in one line by wildcard wouldn't work.
        . "$functionFile"
    done
fi
    
# Load in host-specific definitions, if any exist.
if [ -f "$audioToolsDir/bash/functions/hosts/${HOSTNAME%-*}.sh" ]; then
    . "$audioToolsDir/bash/functions/hosts/${HOSTNAME%-*}.sh"
fi

