
export soundToolsDir="${__current_module_dir:-$HOME/tools/sound-tools}"

if [ -d "$soundToolsDir/bash/functions" ]; then
    for functionFile in $soundToolsDir/bash/functions/*sh; do
        # Note: Sourcing in one line by wildcard wouldn't work.
        . "$functionFile"
    done
fi
    
# Load in host-specific definitions, if any exist.
if [ -f "$soundToolsDir/bash/functions/hosts/${HOSTNAME%-*}.sh" ]; then
    . "$soundToolsDir/bash/functions/hosts/${HOSTNAME%-*}.sh"
fi

